### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by punitdarji** [RickdeJager/cupshax#4]
```
Traceback (most recent call last):
  File "/home/<>/cupshax/cupshax.py", line 275, in <module>
    main()
  File "/home/<>/cupshax/cupshax.py", line 267, in main
    server = IPPServer((args.ip, args.port), IPPRequestHandler, printer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<>/cupshax/venv/lib/python3.11/site-packages/ippserver/server.py", line 155, in __init__
    socketserver.ThreadingTCPServer.__init__(self, address, request_handler)  # old style class!
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address
Exception ignored in: <function Discovery.__del__ at 0x7f0e985049a0>
Traceback (most recent call last):
  File "/home/<>/cupshax/cupshax.py", line 67, in __del__
    self.close()
  File "/home/<>/cupshax/cupshax.py", line 63, in close
    self.zeroconf.unregister_service(self.service_info)
  File "/home/<>/cupshax/venv/lib/python3.11/site-packages/zeroconf/_core.py", line 699, in unregister_service
    run_coro_with_timeout(
  File "/home/<>/cupshax/venv/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 86, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked: 
```

I am using Kali Linux and Python 3.11. I have installed the required packages. When I tried on first time it was working charm. After I restarted the service it was sowing the above error.

**Comment by mahen23** [comment]
try localhost first

**Comment by punitdarji** [comment]
I tried on localhost but same error.

**Comment by cyberxploithausa** [comment]
Same problem here:
```
[+] Wrapping command in base64...
[+] Command: echo dG91Y2ggL3RtcC9wd24=|base64 -d|sh
Traceback (most recent call last):
  File "/home/user/Desktop/research/cve2024-47076_CUPS/cupshax/cupshax.py", line 275, in <module>
    main()
  File "/home/user/Desktop/research/cve2024-47076_CUPS/cupshax/cupshax.py", line 267, in main
    server = IPPServer((args.ip, args.port), IPPRequestHandler, printer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/ippserver/server.py", line 155, in __init__
    socketserver.ThreadingTCPServer.__init__(self, address, request_handler)  # old style class!
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address
Exception in thread Thread-1 (register):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Desktop/research/cve2024-47076_CUPS/cupshax/cupshax.py", line 58, in register
    self.zeroconf.register_service(self.service_info)
  File "/home/user/.local/lib/python3.11/site-packages/zeroconf/_core.py", line 321, in register_service
    run_coro_with_timeout(
  File "/home/user/.local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 113, in run_coro_with_timeout
    return asyncio.run_coroutine_threadsafe(aw, loop).result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/user/.local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 97, in await_awaitable
    task = await aw
           ^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/zeroconf/_core.py", line 351, in async_register_service
    await self.async_check_service(info, allow_name_change, cooperating_responders, strict)
  File "/home/user/.local/lib/python3.11/site-packages/zeroconf/_core.py", line 544, in async_check_service
    raise NonUniqueNameException
zeroconf._exceptions.NonUniqueNameException
Exception ignored in: <function Discovery.__del__ at 0x7f492627eac0>
Traceback (most recent call last):
  File "/home/user/Desktop/research/cve2024-47076_CUPS/cupshax/cupshax.py", line 67, in __del__
    self.close()
  File "/home/user/Desktop/research/cve2024-47076_CUPS/cupshax/cupshax.py", line 63, in close
    self.zeroconf.unregister_service(self.service_info)
  File "/home/user/.local/lib/python3.11/site-packages/zeroconf/_core.py", line 464, in unregister_service
    run_coro_with_timeout(
  File "/home/user/.local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 117, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked:
```

The above error prompts when am trying to use different ip on the same network but locally it works

**Comment by RickdeJager** [comment]
The IP that you're giving as an argument is that IP that targets should connect back to.  

You can not start a listener on an IP that's not assigned to you. Likewise, starting a listener on localhost is not going to be of any use, unless of course you are trying to attack your own host.  

If you're not sure which IP you need, you can try with something like `python -m http.server --bind <IP>` and see if the target can reach the python listener.  

Unless there's an actual issue with this repo, I'll close the issue soon. This just looks you're giving it the wrong IP address.
